### PR TITLE
Add a weak reference to the parent feed of an item

### PR DESCRIPTION
**Pull request by mdom**

### CODE REVIEW

**Comment by dotandimet** [comment]
So your items can do `$self->feed->source`?
Makes sense.

**Comment by mdom** [comment]
That's exactly my use case... :) Thanks for merging both PRs so fast!

**Comment by dotandimet** [comment]
BTW, sorry about dragging my feet with releasing the module to CPAN, but life and work have been a bit hectic and I've got a few cleanups and bikeshedings I'd like to do before the release.
Maybe I'll open bugs for them.

**Comment by mdom** [comment]
No worries, i know the feeling. And it seems we're still working out some changes for Mojo::Feed. Not that this should prevent you from uploading it to CPAN... :)

**Pull request merged**
